[package]
name = "deitos-verifier"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1", features = ["full"] }
reqwest = "0.11"
md5 = "0.7.0"
warp = "0.3"
rand = "0.8"
sha2 = "0.10.8"
envmnt = "0.10"
once_cell = "1.19"